version: '3.5'
services:
  task-gin-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=task
    # volumes:
    #   - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  task-gin-backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_HOST=task-gin-postgres
      - DB_PORT=5432
      - DB_DATABASE=task
    depends_on:
      - task-gin-postgres
  # task-gin-frontend:
  #   build: ./frontend
  #   ports:
  #       - 3000:3001
