DROP TABLE IF EXISTS tasks;
CREATE SEQUENCE id START 1;
CREATE TABLE tasks (
    ID serial PRIMARY KEY,
    TITLE VARCHAR NOT NULL,
    ACCTION_TIME INT NOT NULL,
    CREATE_TIME INT NOT NULL,
    UPDATE_TIME INT NOT NULL,
    IS_FINISHED BIT
);

DROP TABLE IF EXISTS details;
CREATE TABLE details (
    ID serial PRIMARY KEY,
    OBJECT_TASK_FK INT NOT NULL,
    OBJECT_NAME VARCHAR NOT NULL,
    IS_FINISHED BIT
);
